### ISSUE TITLE
(World specific) Pallete filter query throws NullPointerExceptions

### ISSUE THREAD

**Issue by darkinnit** [Querz/mcaselector#117]
**Describe the bug**
NOTE: This bug does not seem to be reproducable in new worlds, but I have provided an existing region file that causes it.
When using the Filter Chunks option in the nether of a pre-existing world with a Pallete filter of any valid minecraft block (e.g. obsidian, stone_bricks, sign), the filter progress will get so far and then hang. In the console many lines of `java.lang.NullPointerException` are printed, including `Exception in thread "pool-6
-thread-#"  java.lang.NullPointerException`

Selecting smaller/different x/y-pos filters does not seem to help although sometimes some chunks are successfully selected before it hangs. I have tried this against an existing 1.15.2 world and a 1.16 world that was updated using `--forceUpgrade`. I cannot reproduce the bug with a new world (even trying some old Minecraft versions)

Example console output:
```
Exception in thread "pool-6-thread-32" java.lang.NullPointerException
Exception in thread "pool-6-thread-43" java.lang.NullPointerException
Exception in thread "pool-6-thread-27" java.lang.NullPointerException
Exception in thread "pool-6-thread-26" Exception in thread "pool-6-thread-44" java.lang.NullPointerException
java.lang.NullPointerException
Exception in thread "pool-6-thread-40" Exception in thread "pool-6-thread-50" Exception in thread "pool-6-thread-41" java.lang.NullPointerException
Exception in thread "pool-6-thread-54" Exception in thread "pool-6-thread-51" java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
Exception in thread "pool-6-thread-45" java.lang.NullPointerException
Exception in thread "pool-6-thread-58" java.lang.NullPointerException
Exception in thread "pool-6-thread-67" java.lang.NullPointerException
```

With debug logs enabled:
```
chunk filter query: Palette contains "obsidian"
map update #309: 0.293400ms
adding LoadDataJob MCASelectFilterLoadJob for r.0.8.mca to executor queue
read 1519616 bytes from C:\Users\Andrew\Desktop\nether update\bug\r.0.8.mca in 1.963100ms
java.lang.Exception: validation error
        at net.querz.mcaselector.debug.Debug.dumpException(Debug.java:80)
        at net.querz.mcaselector.validation.ValidationHelper.withDefault(ValidationHelper.java:14)
        at net.querz.mcaselector.version.anvil113.Anvil113ChunkFilter.matchBlockNames(Anvil113ChunkFilter.java:21)
        at net.querz.mcaselector.filter.PaletteFilter.contains(PaletteFilter.java:42)
        at net.querz.mcaselector.filter.PaletteFilter.contains(PaletteFilter.java:15)
        at net.querz.mcaselector.filter.TextFilter.matches(TextFilter.java:38)
        at net.querz.mcaselector.filter.GroupFilter.matches(GroupFilter.java:79)
        at net.querz.mcaselector.io.MCAFile.getFilteredChunks(MCAFile.java:285)
        at net.querz.mcaselector.io.ChunkFilterSelector$MCASelectFilterProcessJob.execute(ChunkFilterSelector.java:110)
        at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
        at net.querz.mcaselector.version.anvil113.Anvil113ChunkFilter.lambda$matchBlockNames$1(Anvil113ChunkFilter.java:21)
        at net.querz.mcaselector.version.anvil113.Anvil113ChunkFilter$$Lambda$531/870246408.get(Unknown Source)
        at net.querz.mcaselector.validation.ValidationHelper.withDefault(ValidationHelper.java:12)
        at net.querz.mcaselector.version.anvil113.Anvil113ChunkFilter.matchBlockNames(Anvil113ChunkFilter.java:21)
        at net.querz.mcaselector.filter.PaletteFilter.contains(PaletteFilter.java:42)
        at net.querz.mcaselector.filter.PaletteFilter.contains(PaletteFilter.java:15)
        at net.querz.mcaselector.filter.TextFilter.matches(TextFilter.java:38)
        at net.querz.mcaselector.filter.GroupFilter.matches(GroupFilter.java:79)
        at net.querz.mcaselector.io.MCAFile.getFilteredChunks(MCAFile.java:285)
        at net.querz.mcaselector.io.ChunkFilterSelector$MCASelectFilterProcessJob.execute(ChunkFilterSelector.java:110)
        at net.querz.mcaselector.io.ProcessDataJob.run(ProcessDataJob.java:21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
took 190.729000ms to delete chunk indices in r.0.8.mca
map update #310: 0.670900ms
 ... 838 more of null: Anvil113ChunkFilter.java net.querz.mcaselector.version.anvil113.Anvil113ChunkFilter lambda$matchBlockNames$1 L21
 ... 838 more of validation error: Debug.java net.querz.mcaselector.debug.Debug dumpException L80
```

**To Reproduce**
1. Open a Nether region
2. Click on Tools - Filter Chunks
3. Add a filter of Palette contains "obsidian"
4. See errors in console and progress bar hangs

**Expected behavior**
Chunks containing obsidian blocks to be selected.

**Screenshots and other files**
MCA file that reproduces the bug attached
[r.0.8.mca.zip](https://github.com/Querz/mcaselector/files/4820351/r.0.8.mca.zip)
(Note, as this region is a bit far south, you need to zoom out and/or pan to the south a little for it to show up in the preview)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: 1.8.0_51
- Version 1.11

**Comment by darkinnit** [comment]
I meant to add, this bug does not seem to occur with other filter options, such as InhabitedTime

**Comment by Querz** [comment]
It looks like in that Minecraft version there are Sections without a Palette:
![image](https://user-images.githubusercontent.com/8278330/85430147-073b7580-b580-11ea-99f8-5da1d28b8280.png)
The exception that is thrown does not cause the filter to stop, it's rather an information that the filter encountered something unexpected.
Fixed it in [this commit](https://github.com/Querz/mcaselector/commit/08c51f7d36497fff3543bfc1938e5d61bf952080) and will be in the next release, probably over the next few days.

**Comment by darkinnit** [comment]
Amazing! Thanks for the fast response! Also, many thanks for an incredibly useful tool

**Comment by Querz** [comment]
Working with someone who knows how to create a proper bug report is always a pleasure!

The fix for this bug is now live in release [1.11.1](https://github.com/Querz/mcaselector/releases/tag/1.11.1).

**Comment by darkinnit** [comment]
Hi,

This helped with the issue but did not completely resolve it - in particular some chunks were not being selected that were known to match the filter.

I noticed that for chunks that are not populated, the Sections tag is a zero length LongArrayTag instead of a ListTag.

I managed to get it fully working locally by changing [this line](https://github.com/Querz/mcaselector/commit/08c51f7d36497fff3543bfc1938e5d61bf952080#diff-8398a803a80b7c87b9c92a28540526dfR19) from:
`if (rawSections == null) {`
to
`if (rawSections == null || rawSections instanceof LongArrayTag) {`

What are your thoughts? Should I raise a PR?

**Comment by Querz** [comment]
I changed this line now to your suggestion and changed [this line](https://github.com/Querz/mcaselector/blob/master/src/main/java/net/querz/mcaselector/version/anvil113/Anvil113ChunkDataProcessor.java#L27) too. If this is part of Minecraft's chunk format to have empty LongArrayTags instead of ListTags when the chunk is not populated, it should not throw an exception when drawing the chunk either.
